"""Add fecha_nacimiento and sexo to usuarios

Revision ID: 359957ca45a1
Revises: a80805b3e7a9
Create Date: 2026-07-16 08:30:24.180268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359957ca45a1'
down_revision: Union[str, Sequence[str], None] = 'a80805b3e7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('fecha_nacimiento', sa.Date(), nullable=True))
    op.add_column('usuarios', sa.Column('sexo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'sexo')
    op.drop_column('usuarios', 'fecha_nacimiento')
    # ### end Alembic commands ###
